version: '3.8'

services:
  flask_app:
    image: my-flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - FLASK_ENV=development
      - GIT_PYTHON_REFRESH=quiet
      - GIT_PYTHON_GIT_EXECUTABLE=/usr/bin/git


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus_docker.yml"
    volumes:
      - ./configs/prometheus_docker.yml:/etc/prometheus/prometheus_docker.yml
    ports:
      - "9090:9090"

  