version: '3.8'

services:
  flask_app:
    image: my-flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - FLASK_ENV=development
      - GIT_PYTHON_REFRESH=quiet
      - GIT_PYTHON_GIT_EXECUTABLE=/usr/bin/git


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus_docker.yml"
    volumes:
      - ./configs/prometheus_docker.yml:/etc/prometheus/prometheus_docker.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana runs on port 3000
    volumes:
      - grafana_data:/var/lib/grafana  # Persistent storage for Grafana dashboards and settings
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Default admin user
      - GF_SECURITY_ADMIN_PASSWORD=rita123/  # Default admin password

volumes:
  grafana_data: