name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install PyYAML==5.4.1 --no-build-isolation  # Avoid build isolation for PyYAML
          pip install poetry
          poetry install
      - name: Lint with Ruff
        run: poetry run ruff check .
      - name: Check with Flake8
        run: poetry run flake8 src/ tests/
      - name: Run Black
        run: poetry run black --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install PyYAML==5.4.1 --no-build-isolation  # Avoid build isolation for PyYAML
          pip install poetry
          poetry install
      - name: Run Tests
        run: poetry run pytest --cov=src tests/


